#
# The MIT License (MIT)
#
# Copyright (c) 2026  Steffen Nuessle
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

import argparse
import csv
import os
import re
import sys

import util

import gn


class Dispatcher:
    def __init__(self):
        self.diagnostics = []
        self.regex = re.compile(
            r'(?P<path>[\w/.-]+):'
            r'(?P<line>\d+):'
            r'(?P<column>\d+): '
            r'(?P<severity>\w+): '
            r'(?P<message>[^[]+)'
            r'\[(?P<diagnostic>.*)\]'
        )

    def parse_diagnostics(self, iteratable):
        for line in iteratable:
            if match := self.regex.match(line):
                item = match.groupdict()

                self.diagnostics.append(item)

    def add_metadata(self, metadata):
        if not metadata:
            return

        keys = ['target', 'template']

        for item in self.diagnostics:
            if data := metadata.get_file_metadata(item['path']):
                for key in keys:
                    item[key] = data[key]

    def write_output(self, out):
        if not out:
            return

        if len(self.diagnostics) != 0:
            keys = list(self.diagnostics[0].keys())
        else:
            keys = list(self.regex.groupindex.keys())

        writer = csv.DictWriter(
            out,
            fieldnames=keys,
            lineterminator=os.linesep,
            quoting=csv.QUOTE_ALL,
        )
        writer.writeheader()
        writer.writerows(self.diagnostics)

    def check_thresholds(self, thresholds):
        if not thresholds:
            return True

        # Count how many messages of each diagnostic were emitted
        summary = {}

        for item in self.diagnostics:
            diag = item['diagnostic']

            if diag not in summary:
                summary[diag] = 1
                continue

            summary[diag] += 1

        # Check the threshold for each diagnostic
        check_ok = True

        for diag, count in summary.items():
            threshold = thresholds.get(diag, -1)
            if threshold < 0 or threshold >= count:
                print(
                    (
                        f'{sys.argv[0]}: note: [{diag}] below threshold '
                        f'({count}/{threshold})'
                    ),
                    file=sys.stderr,
                )
                continue

            check_ok = False
            print(
                (
                    f'{sys.argv[0]}: error: [{diag}] threshold exceeded '
                    f'({count}/{threshold})'
                ),
                file=sys.stderr,
            )

        return check_ok


def main():
    parser = argparse.ArgumentParser(
        description='Dispatch clang-tidy diagnostic messages.'
    )
    parser.add_argument(
        'input',
        help='A file containing diagnostics generated by clang-tidy.',
        type=lambda x: open(x, 'r'),
    )
    parser.add_argument(
        '-o',
        help='The generated output file.',
        required=False,
        default=None,
        type=lambda x: open(x, 'w', newline=''),
    )
    parser.add_argument(
        '--metadata',
        help="The project's metadata file.",
        required=False,
        default=None,
        type=gn.Metadata.from_file,
    )
    parser.add_argument(
        '--threshold',
        help='Specify a threshold for a specific type of diagnostic.',
        nargs='*',
        metavar='DIAG=THRESHOLD',
        default=[],
        type=str,
    )

    args = parser.parse_args()

    thresholds = {
        k: int(v) for k, v in util.invoke_split(args.threshold, '=', maxsplit=1)
    }

    dispatcher = Dispatcher()
    dispatcher.parse_diagnostics(args.input)
    dispatcher.add_metadata(args.metadata)
    dispatcher.write_output(args.o)
    check_ok = dispatcher.check_thresholds(thresholds)

    path = os.path.abspath(args.input.name)
    print(f'Analysis Output : {path}', file=sys.stderr)

    if args.o:
        path = os.path.abspath(args.o.name)
        print(f'Analysis Report : {path}', file=sys.stderr)

    exit_code = check_ok is False
    sys.exit(exit_code)


if __name__ == '__main__':
    main()
