#
# Copyright (C) 2023  Steffen Nuessle
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 6"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: [archlinux-build]
    if: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create docker image
        run: |
          make -f docker/Makefile ${{ matrix.docker_image }} CMD=true
      - name: Configure build system
        run: |
          make -f docker/Makefile ${{ matrix.docker_image }} CMD=" \
              gn gen build"
      - name: Perform software build
        run: |
          make -f docker/Makefile ${{ matrix.docker_image }} CMD=" \
              ninja \
                -C build \
                -k 0 \
                all"


